### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by Suraporn** [Suraporn/nba_player_comparison#1]
A peer review issue for `nba_player_comparison`.

**Comment by CChCheChen** [comment]
Great job @Suraporn!!!!

A nice tool to do NBA player comparison and it is indeed an extension from our milestone project.

Some improve can be:
1. The 2 player selections can be centred as well also make a margin between them, for better visual
2. Logo did not render/display as expected
3. It would be nice to have player selections and stats plot, simply in 2 separate rows (2 player selections in 1 row and 2 stats plot in 1 row) for large window sizes.

It is great to include the offensive and defensive comparisons, I really liked this part!

Overall, WONDERFUL JOB!

**Comment by Althrun-sun** [comment]
Good job Nate,
Nate's NBA player comparison app is an impressive tool that provides an intuitive way to compare statistical data and performance between different players. The app's interface is very user-friendly, allowing users to easily select the players they want to compare and view various statistics and charts. Additionally, the app provides detailed information and historical records about each player, making it easy to delve deeper into each player's background. Overall, it is a highly impressive app that provides a lot of enjoyment and benefits for both NBA fans and casual users alike.

**Comment by pengzh313** [comment]
It is a nice work to expand on our group project. I like the simple layout. It is very straightforward for users to explore the app and obtain the visualized information. 

Two things may be considered:
1. Add explanations for the abbreviations in the table, such as "PF", "SF", "SG".
2. Round the numbers in the table since some results may have large decimal places. Such as if selecting Kirk Snyder, you will see multiple decimal numbers in the results.
